### ISSUE TITLE
update build tools for new repo name

### ISSUE THREAD

**Issue by nomicode** [crate/crate-docs-build#10]
today, we changed the repo name from `crate-docs-utils` to `docs`. the build system needs updating to point to the new repo URL and the `utils.json` file (and other things, possibly?) need updating to fit in with the new name

- [x] update URL in makefile
- [ ] do a new release
- [ ] update all docs projects to latest makefile version

**Comment by nomicode** [comment]
subsumed into https://github.com/crate/docs-private/issues/75
